@startuml Mapping
hide empty members
left to right direction

class "KeysymEntry" {}
class "Mnemonic" {
  mnemonic: String
}
class "Ucp" {
  ucp: int
}
class "Code" {
  code: int
}

"KeysymEntry" <|-- "Mnemonic"
"KeysymEntry" <|-- "Ucp"
"KeysymEntry" <|-- "Code"

class "KeyboardMap" {
  entries(xKeyName: String): List<KeysymEntry>
  xKeyNames(mnemonic: String): Set<String>
  xKeyNames(ucp: int): Set<String>
  xKeyNames(code: int): Set<String>
  canonicalize(canonicalXKeyNameByAlias: Map<String, String>): KeyboardMap
}

class "SimpleSymbolsReader" {
  read(CharSource source): KeyboardMap
}

KeysymEntry -[hidden]> KeyboardMap
KeyboardMap -[hidden]> SimpleSymbolsReader

@enduml